#!/bin/bash

usage () {
cat << EOF

WARNING: THIS IS A LOGIN NODE
WARNING: DOCKER IS NOT INSTALLED HERE
WARNING: THERE ARE NO GPU CARDS HERE
WARNING: USE THE JOB SCHEDULER TO ACCESS COMPUTE NODES

Usage: $0 COMMAND

A front-end to the Docker command.
Sets site-specific options and then calls relevant Docker command.
Only a subset of functionality is currently implemented.

Commands:
  images      List the cached output of "docker images"
  run         Submit an interactive job to launch a container

EOF
}

docker_run(){
if [ $# -eq 0 ] ; then usage ; echo No image specified ; exit 1 ; fi
# submit an interactive PBS job which runs container and gives a tty
command="qsub -I -q dgx-dev -l walltime=2:00:00 -- /usr/local/bin/nscc-docker run -t $1"
echo INFO: Submitting interactive job to PBS
echo INFO: $command
exec $command
}

docker_images(){
file="/var/run/docker-images"
tty > /dev/null 2>&1 && less "$file" || cat "$file"
}

subcommand=$1
shift
case $subcommand in \
  run) docker_run $* ;;
  images) docker_images ;;
  *) usage ;;
esac
