#!/bin/bash
# access command directly for users who are in docker group and root
if [ $UID -eq 0 ] ; then exec /usr/bin/%NAME% "$@" ; fi
egrep '^docker:.*:(.*,|)'"$USER"'(,|$)' /etc/group > /dev/null 2>&1 && exec /usr/bin/%NAME% "$@"

usage () {
cat << EOF

Usage: $0 COMMAND

A transparent front-end to the Docker command.
Only a subset of functionality is currently implemented.

Commands:
  images      List images
  ps          List containers
  rm          Remove one or more containers
  run         Run a command in a new container (not yet implemented)
  stop        Stop one or more running containers

Run 'docker COMMAND --help' for more information on a command.

EOF
}

not_implemented(){
usage
echo
echo Not yet implemented: $*
exit 1
}

libexec=%LIBEXEC%
subcommand=$1
shift
case $subcommand in \
  images|ps|rm|stop) exec $libexec/docker.$subcommand "$@" ;;
  -*|'') usage ;;
  *) not_implemented $subcommand $* ;;
esac
